package cleanup

import (
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"sync"
)

var tsPattern = regexp.MustCompile(`\d{4}-\d{2}-\d{2}[T ]|^\[\d{4}-\d{2}`)

var classifyExts = map[string]bool{
	".md": true, ".txt": true, ".json": true, ".yaml": true, ".yml": true,
	".go": true, ".ts": true, ".js": true, ".sh": true, ".py": true,
	".toml": true, ".cfg": true, ".ini": true,
}

// Classify reads first 512 bytes of ambiguous files and sets Content.
func Classify(files []FileInfo) error {
	type work struct{ idx int }

	queue := make(chan work, len(files))
	for i := range files {
		f := &files[i]
		if f.IsDir || f.IsSymlink {
			continue
		}
		if f.Size <= 0 || f.Size >= 1<<20 {
			continue
		}
		if f.Content != ContentUnknown {
			continue
		}
		ext := fileExt(f.Path)
		if ext != "" && !classifyExts[ext] {
			continue
		}
		queue <- work{i}
	}
	close(queue)

	workers := runtime.NumCPU()
	var wg sync.WaitGroup
	wg.Add(workers)
	for range workers {
		go func() {
			defer wg.Done()
			for w := range queue {
				files[w.idx].Content = classifyFile(files[w.idx].Path)
			}
		}()
	}
	wg.Wait()
	return nil
}

func classifyFile(path string) ContentClass {
	f, err := os.Open(path)
	if err != nil {
		return ContentUnknown
	}
	defer f.Close()
	buf := make([]byte, 512)
	n, _ := f.Read(buf)
	if n == 0 {
		return ContentUnknown
	}
	data := string(buf[:n])
	return classifyContent(data)
}

func classifyContent(data string) ContentClass {
	lower := strings.ToLower(data)

	// 1. Generated
	if strings.Contains(data, "Code generated") ||
		strings.Contains(data, "AUTO-GENERATED") ||
		strings.Contains(data, "Auto-generated") ||
		strings.Contains(data, "DO NOT EDIT") ||
		strings.Contains(data, "do not edit") ||
		strings.Contains(lower, "generated by") {
		return ContentGenerated
	}

	lines := splitLines(data)

	// 2. Scratch/TodoOnly: every non-empty line starts with a marker
	if len(lines) > 0 && allScratchLines(lines) {
		return ContentTodoOnly
	}

	// 3. LogDump: >50% of lines match timestamp pattern
	if len(lines) > 0 {
		matches := 0
		for _, l := range lines {
			if tsPattern.MatchString(l) {
				matches++
			}
		}
		if matches*2 > len(lines) {
			return ContentLogDump
		}
	}

	// 4. Config
	firstLine := ""
	if len(lines) > 0 {
		firstLine = strings.TrimSpace(lines[0])
	}
	if strings.HasPrefix(firstLine, "{") || strings.HasPrefix(firstLine, "---") {
		return ContentConfig
	}
	// [ only triggers config for JSON arrays or TOML headers, not markdown links
	if strings.HasPrefix(firstLine, "[") && !strings.Contains(firstLine, "](") {
		return ContentConfig
	}
	if len(lines) > 0 {
		kvCount := 0
		for _, l := range lines {
			if isKVLine(l) {
				kvCount++
			}
		}
		if kvCount*2 > len(lines) {
			return ContentConfig
		}
	}

	return ContentMeaningful
}

func splitLines(data string) []string {
	raw := strings.Split(data, "\n")
	out := make([]string, 0, len(raw))
	for _, l := range raw {
		if strings.TrimSpace(l) != "" {
			out = append(out, l)
		}
	}
	return out
}

var scratchPrefixes = []string{"TODO", "FIXME", "HACK", "XXX", "- [ ]", "- [x]", "- [X]"}

func allScratchLines(lines []string) bool {
	for _, l := range lines {
		matched := false
		for _, p := range scratchPrefixes {
			if strings.HasPrefix(strings.TrimSpace(l), p) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

func isKVLine(l string) bool {
	trimmed := strings.TrimSpace(l)
	// YAML-style: key with no spaces followed by ": "
	if idx := strings.Index(trimmed, ": "); idx > 0 {
		key := trimmed[:idx]
		if !strings.Contains(key, " ") && len(key) < 40 {
			return true
		}
	}
	// INI-style: key = value
	if idx := strings.Index(trimmed, " = "); idx > 0 {
		key := trimmed[:idx]
		if !strings.Contains(key, " ") && len(key) < 40 {
			return true
		}
	}
	return false
}

func fileExt(path string) string {
	return filepath.Ext(path)
}
