package cleanup

import (
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"sync"
	"time"
)

var tsPattern = regexp.MustCompile(`\d{4}-\d{2}-\d{2}[T ]|^\[\d{4}-\d{2}`)

var classifyExts = map[string]bool{
	".md": true, ".txt": true, ".json": true, ".yaml": true, ".yml": true,
	".go": true, ".ts": true, ".js": true, ".sh": true, ".py": true,
	".toml": true, ".cfg": true, ".ini": true,
}

// Classify reads first and last 256 bytes of ambiguous files and sets Content.
func Classify(files []FileInfo) error {
	type work struct{ idx int }

	queue := make(chan work, len(files))
	for i := range files {
		f := &files[i]
		if f.IsDir || f.IsSymlink {
			continue
		}
		if f.Size <= 0 || f.Size >= 1<<20 {
			continue
		}
		if f.Content != ContentUnknown {
			continue
		}
		ext := fileExt(f.Path)
		if ext != "" && !classifyExts[ext] {
			continue
		}
		queue <- work{i}
	}
	close(queue)

	workers := runtime.NumCPU()
	var wg sync.WaitGroup
	wg.Add(workers)
	for range workers {
		go func() {
			defer wg.Done()
			for w := range queue {
				files[w.idx].Content = classifyFile(files[w.idx].Path, files[w.idx].Size)
			}
		}()
	}
	wg.Wait()
	enrichMIME(files)
	return nil
}

func classifyFile(path string, knownSize int64) ContentClass {
	f, err := os.Open(path)
	if err != nil {
		return ContentUnknown
	}
	defer f.Close()

	size := knownSize

	// Read head (first 256 bytes).
	headBuf := make([]byte, 256)
	hn, _ := f.Read(headBuf)
	if hn == 0 {
		return ContentUnknown
	}
	head := headBuf[:hn]

	// Read tail (last 256 bytes) if file is large enough that tail differs from head.
	var data []byte
	if size > 512 {
		tailBuf := make([]byte, 256)
		f.Seek(-256, io.SeekEnd)
		tn, _ := f.Read(tailBuf)
		if tn > 0 {
			data = make([]byte, hn+tn)
			copy(data, head)
			copy(data[hn:], tailBuf[:tn])
		} else {
			data = head
		}
	} else {
		// Small file — read the whole thing (up to 512 bytes).
		// We already have the first 256. Read more if available.
		moreBuf := make([]byte, 256)
		mn, _ := f.Read(moreBuf)
		if mn > 0 {
			data = make([]byte, hn+mn)
			copy(data, head)
			copy(data[hn:], moreBuf[:mn])
		} else {
			data = head
		}
	}

	return classifyContent(string(data))
}

func classifyContent(data string) ContentClass {
	lower := strings.ToLower(data)

	// 1. Generated
	if strings.Contains(data, "Code generated") ||
		strings.Contains(data, "AUTO-GENERATED") ||
		strings.Contains(data, "Auto-generated") ||
		strings.Contains(data, "DO NOT EDIT") ||
		strings.Contains(data, "do not edit") ||
		strings.Contains(lower, "generated by") {
		return ContentGenerated
	}

	lines := splitLines(data)

	// 2. Scratch/TodoOnly: every non-empty line starts with a marker
	if len(lines) > 0 && allScratchLines(lines) {
		return ContentTodoOnly
	}

	// 3. LogDump: >50% of lines match timestamp pattern
	if len(lines) > 0 {
		matches := 0
		for _, l := range lines {
			if tsPattern.MatchString(l) {
				matches++
			}
		}
		if matches*2 > len(lines) {
			return ContentLogDump
		}
	}

	// 4. Config
	firstLine := ""
	if len(lines) > 0 {
		firstLine = strings.TrimSpace(lines[0])
	}
	if strings.HasPrefix(firstLine, "{") || strings.HasPrefix(firstLine, "---") {
		return ContentConfig
	}
	// [ only triggers config for JSON arrays or TOML headers, not markdown links
	if strings.HasPrefix(firstLine, "[") && !strings.Contains(firstLine, "](") {
		return ContentConfig
	}
	if len(lines) > 0 {
		kvCount := 0
		for _, l := range lines {
			if isKVLine(l) {
				kvCount++
			}
		}
		if kvCount*2 > len(lines) {
			return ContentConfig
		}
	}

	return ContentMeaningful
}

func splitLines(data string) []string {
	raw := strings.Split(data, "\n")
	out := make([]string, 0, len(raw))
	for _, l := range raw {
		if strings.TrimSpace(l) != "" {
			out = append(out, l)
		}
	}
	return out
}

var scratchPrefixes = []string{"TODO", "FIXME", "HACK", "XXX", "- [ ]", "- [x]", "- [X]"}

func allScratchLines(lines []string) bool {
	for _, l := range lines {
		matched := false
		for _, p := range scratchPrefixes {
			if strings.HasPrefix(strings.TrimSpace(l), p) {
				matched = true
				break
			}
		}
		if !matched {
			return false
		}
	}
	return true
}

func isKVLine(l string) bool {
	trimmed := strings.TrimSpace(l)
	// YAML-style: key with no spaces followed by ": "
	if idx := strings.Index(trimmed, ": "); idx > 0 {
		key := trimmed[:idx]
		if !strings.Contains(key, " ") && len(key) < 40 {
			return true
		}
	}
	// INI-style: key = value
	if idx := strings.Index(trimmed, " = "); idx > 0 {
		key := trimmed[:idx]
		if !strings.Contains(key, " ") && len(key) < 40 {
			return true
		}
	}
	return false
}

func fileExt(path string) string {
	return filepath.Ext(path)
}

// enrichMIME uses the file command to detect MIME types for files still at ContentUnknown.
func enrichMIME(files []FileInfo) {
	var indices []int
	for i := range files {
		f := &files[i]
		if f.IsDir || f.IsSymlink || f.Content != ContentUnknown || f.Size <= 0 {
			continue
		}
		indices = append(indices, i)
	}
	if len(indices) == 0 {
		return
	}

	// Batch in groups of 50.
	for start := 0; start < len(indices); start += 50 {
		end := start + 50
		if end > len(indices) {
			end = len(indices)
		}
		batch := indices[start:end]

		args := []string{"--mime-type", "-b"}
		for _, idx := range batch {
			args = append(args, files[idx].Path)
		}

		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		cmd := exec.CommandContext(ctx, "file", args...)
		out, err := cmd.Output()
		cancel()
		if err != nil {
			continue
		}

		lines := strings.Split(strings.TrimSpace(string(out)), "\n")
		for j, idx := range batch {
			if j >= len(lines) {
				break
			}
			mime := strings.TrimSpace(lines[j])
			if cls := mimeToClass(mime); cls != ContentUnknown {
				files[idx].Content = cls
			}
		}
	}
}

func mimeToClass(mime string) ContentClass {
	switch mime {
	case "application/json",
		"application/xml",
		"text/xml",
		"application/toml",
		"application/x-yaml",
		"text/x-yaml":
		return ContentConfig
	default:
		return ContentUnknown
	}
}
