package cleanup

import (
	"strings"
	"testing"
)

// --- classifyContent tests ---

func TestClassifyContent(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  ContentClass
	}{
		{name: "generated header", input: "// Code generated by foo DO NOT EDIT", want: ContentGenerated},
		{name: "auto-generated", input: "# Auto-generated file\ndo not edit", want: ContentGenerated},
		{name: "generated by tool", input: "// generated by protoc-gen-go", want: ContentGenerated},
		{name: "todo only", input: "TODO: fix this\nFIXME: broken\nHACK: workaround", want: ContentTodoOnly},
		{name: "checkbox list", input: "- [ ] task1\n- [x] task2\n- [ ] task3", want: ContentTodoOnly},
		{name: "log dump", input: "[2024-01-01] Error: foo\n[2024-01-02] Error: bar\n[2024-01-03] OK", want: ContentLogDump},
		{name: "yaml frontmatter", input: "---\nname: foo\nversion: 1.0", want: ContentConfig},
		{name: "json object", input: `{"key": "value"}`, want: ContentConfig},
		{name: "kv pairs", input: "key: value\nother: thing\nthird: item", want: ContentConfig},
		{name: "meaningful prose", input: "This is a meaningful document with real content.", want: ContentMeaningful},

		// Bug #3: bracket-heavy markdown should NOT be log dump
		{
			name:  "markdown with links is not log dump",
			input: "[link1](url1)\n[link2](url2)\n[link3](url3)\nSome text here",
			want:  ContentMeaningful,
		},
		// Bug #3: TOML section headers should NOT be log dump
		{
			name:  "toml sections not log dump",
			input: "[server]\nhost = localhost\nport = 8080\n[database]\nurl = postgres://",
			want:  ContentConfig,
		},
		// Bug #3: version strings should NOT trigger timestamp
		{
			name:  "version strings not log dump",
			input: "go 1.26.1\nrequire foo v1.2.3\nrequire bar v4.5.6",
			want:  ContentMeaningful,
		},
		// Bug #4: shell script with comments is NOT scratch
		{
			name:  "shell script comments not scratch",
			input: "#!/bin/bash\n# This script installs dependencies\n# Author: vampire\nset -euo pipefail\napt-get update",
			want:  ContentMeaningful,
		},
		// Bug #4: license block is NOT scratch
		{
			name:  "license block not scratch",
			input: "# MIT License\n# Copyright (c) 2024\n# Permission is hereby granted...",
			want:  ContentMeaningful,
		},
		// Bug #4: Python with docstrings is NOT scratch
		{
			name:  "python comments not scratch",
			input: "# -*- coding: utf-8 -*-\n# Module for processing data\nimport os\nimport sys",
			want:  ContentMeaningful,
		},
		// Bug #5: prose with colons is NOT config
		{
			name:  "prose with colons not config",
			input: "This is a sentence: it has meaning.\nAnother thought: quite deep.\nThe point: clarity matters.",
			want:  ContentMeaningful,
		},
		// Bug #5: natural language paragraphs with colons
		{
			name:  "paragraph with colons not config",
			input: "Error handling: always wrap errors.\nTesting: use table-driven tests.\nThis is documentation.",
			want:  ContentMeaningful,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := classifyContent(tc.input)
			if got != tc.want {
				t.Errorf("classifyContent() = %s, want %s\ninput: %q",
					got, tc.want, tc.input)
			}
		})
	}
}

// --- isKVLine tests ---

func TestIsKVLine(t *testing.T) {
	tests := []struct {
		line string
		want bool
	}{
		{"key: value", true},
		{"name: foo", true},
		{"DEBUG = true", true},
		{"This is a sentence: with a colon.", false}, // key has spaces
		{"Another thought: quite deep.", false},       // key has spaces
		{"multi word key: value", false},               // key has spaces
		{"x: y", true},                                 // short key OK
		{strings.Repeat("a", 50) + ": value", false},  // key too long
	}

	for _, tc := range tests {
		t.Run(tc.line, func(t *testing.T) {
			got := isKVLine(tc.line)
			if got != tc.want {
				t.Errorf("isKVLine(%q) = %v, want %v", tc.line, got, tc.want)
			}
		})
	}
}

// --- Score tests ---

func TestScore(t *testing.T) {
	tests := []struct {
		name string
		f    FileInfo
		want int
	}{
		{name: "untracked only", f: FileInfo{Tracked: false}, want: 20},
		{name: "stale 100 days + untracked", f: FileInfo{Tracked: false, StaleDays: 100}, want: 35},
		{name: "stale 200 days + orphaned", f: FileInfo{Tracked: false, StaleDays: 200, Orphaned: true}, want: 70},
		{name: "stale 400 days", f: FileInfo{Tracked: false, StaleDays: 400}, want: 55},       // 20+35
		{name: "empty dir", f: FileInfo{IsDir: true, IsEmpty: true}, want: 50},                 // 20+30
		{name: "tracked not stale", f: FileInfo{Tracked: true}, want: 0},
		{
			name: "all signals capped at 100",
			f: FileInfo{
				Tracked: false, StaleDays: 400, Size: 200 * 1024 * 1024,
				Content: ContentTodoOnly, Orphaned: true, Duplicate: "other.txt",
			},
			want: 100,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := Score(&tc.f)
			if got != tc.want {
				t.Errorf("Score() = %d, want %d", got, tc.want)
			}
		})
	}
}

// --- FindDuplicates tests ---

func TestFindDuplicates(t *testing.T) {
	files := []FileInfo{
		// Backup suffix: config-backup.yaml → config.yaml
		{RelPath: "config.yaml", Size: 100},
		{RelPath: "config-backup.yaml", Size: 100},
		// Basename collision: use non-common name with size > 4KB
		{RelPath: "processor.go", Size: 8192},
		{RelPath: "old/processor.go", Size: 8192},
		// Version suffix: readme-v2.md → readme.md
		{RelPath: "readme.md", Size: 50},
		{RelPath: "readme-v2.md", Size: 50},
		// Unique file: no duplicate
		{RelPath: "unique.txt", Size: 999},
		// Common multi-instance name: should NOT be flagged even with same size
		{RelPath: "cmd/foo/main.go", Size: 200},
		{RelPath: "cmd/bar/main.go", Size: 200},
		// Small basename collision (<=4KB): should NOT be flagged
		{RelPath: "helper.go", Size: 512},
		{RelPath: "lib/helper.go", Size: 512},
	}

	FindDuplicates(files)

	byPath := make(map[string]FileInfo)
	for _, f := range files {
		byPath[f.RelPath] = f
	}

	cases := []struct {
		path     string
		wantDup  string
		hasNoDup bool
	}{
		{path: "config.yaml", hasNoDup: true},
		{path: "config-backup.yaml", wantDup: "config.yaml"},
		{path: "processor.go", hasNoDup: true},
		{path: "old/processor.go", wantDup: "processor.go"},
		{path: "readme.md", hasNoDup: true},
		{path: "readme-v2.md", wantDup: "readme.md"},
		{path: "unique.txt", hasNoDup: true},
		// Common multi-instance: both should have no duplicate
		{path: "cmd/foo/main.go", hasNoDup: true},
		{path: "cmd/bar/main.go", hasNoDup: true},
		// Small files: no basename collision
		{path: "helper.go", hasNoDup: true},
		{path: "lib/helper.go", hasNoDup: true},
	}

	for _, tc := range cases {
		f := byPath[tc.path]
		if tc.hasNoDup {
			if f.Duplicate != "" {
				t.Errorf("%s: expected no duplicate, got %q", tc.path, f.Duplicate)
			}
		} else {
			if f.Duplicate != tc.wantDup {
				t.Errorf("%s: Duplicate = %q, want %q", tc.path, f.Duplicate, tc.wantDup)
			}
		}
	}
}
