package cleanup

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// --- classifyContent tests ---

func TestClassifyContent(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  ContentClass
	}{
		{name: "generated header", input: "// Code generated by foo DO NOT EDIT", want: ContentGenerated},
		{name: "auto-generated", input: "# Auto-generated file\ndo not edit", want: ContentGenerated},
		{name: "generated by tool", input: "// generated by protoc-gen-go", want: ContentGenerated},
		{name: "todo only", input: "TODO: fix this\nFIXME: broken\nHACK: workaround", want: ContentTodoOnly},
		{name: "checkbox list", input: "- [ ] task1\n- [x] task2\n- [ ] task3", want: ContentTodoOnly},
		{name: "log dump", input: "[2024-01-01] Error: foo\n[2024-01-02] Error: bar\n[2024-01-03] OK", want: ContentLogDump},
		{name: "yaml frontmatter", input: "---\nname: foo\nversion: 1.0", want: ContentConfig},
		{name: "json object", input: `{"key": "value"}`, want: ContentConfig},
		{name: "kv pairs", input: "key: value\nother: thing\nthird: item", want: ContentConfig},
		{name: "meaningful prose", input: "This is a meaningful document with real content.", want: ContentMeaningful},

		// Bug #3: bracket-heavy markdown should NOT be log dump
		{
			name:  "markdown with links is not log dump",
			input: "[link1](url1)\n[link2](url2)\n[link3](url3)\nSome text here",
			want:  ContentMeaningful,
		},
		// Bug #3: TOML section headers should NOT be log dump
		{
			name:  "toml sections not log dump",
			input: "[server]\nhost = localhost\nport = 8080\n[database]\nurl = postgres://",
			want:  ContentConfig,
		},
		// Bug #3: version strings should NOT trigger timestamp
		{
			name:  "version strings not log dump",
			input: "go 1.26.1\nrequire foo v1.2.3\nrequire bar v4.5.6",
			want:  ContentMeaningful,
		},
		// Bug #4: shell script with comments is NOT scratch
		{
			name:  "shell script comments not scratch",
			input: "#!/bin/bash\n# This script installs dependencies\n# Author: vampire\nset -euo pipefail\napt-get update",
			want:  ContentMeaningful,
		},
		// Bug #4: license block is NOT scratch
		{
			name:  "license block not scratch",
			input: "# MIT License\n# Copyright (c) 2024\n# Permission is hereby granted...",
			want:  ContentMeaningful,
		},
		// Bug #4: Python with docstrings is NOT scratch
		{
			name:  "python comments not scratch",
			input: "# -*- coding: utf-8 -*-\n# Module for processing data\nimport os\nimport sys",
			want:  ContentMeaningful,
		},
		// Bug #5: prose with colons is NOT config
		{
			name:  "prose with colons not config",
			input: "This is a sentence: it has meaning.\nAnother thought: quite deep.\nThe point: clarity matters.",
			want:  ContentMeaningful,
		},
		// Bug #5: natural language paragraphs with colons
		{
			name:  "paragraph with colons not config",
			input: "Error handling: always wrap errors.\nTesting: use table-driven tests.\nThis is documentation.",
			want:  ContentMeaningful,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := classifyContent(tc.input)
			if got != tc.want {
				t.Errorf("classifyContent() = %s, want %s\ninput: %q",
					got, tc.want, tc.input)
			}
		})
	}
}

// --- isKVLine tests ---

func TestIsKVLine(t *testing.T) {
	tests := []struct {
		line string
		want bool
	}{
		{"key: value", true},
		{"name: foo", true},
		{"DEBUG = true", true},
		{"This is a sentence: with a colon.", false}, // key has spaces
		{"Another thought: quite deep.", false},       // key has spaces
		{"multi word key: value", false},               // key has spaces
		{"x: y", true},                                 // short key OK
		{strings.Repeat("a", 50) + ": value", false},  // key too long
	}

	for _, tc := range tests {
		t.Run(tc.line, func(t *testing.T) {
			got := isKVLine(tc.line)
			if got != tc.want {
				t.Errorf("isKVLine(%q) = %v, want %v", tc.line, got, tc.want)
			}
		})
	}
}

// --- Score tests ---

func TestScore(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		f    FileInfo
		want int
	}{
		{name: "untracked only", f: FileInfo{Findings: []Finding{
			{Rule: RuleUntracked, Severity: SevInfo},
		}}, want: 20},
		{name: "stale 100 days + untracked", f: FileInfo{Findings: []Finding{
			{Rule: RuleUntracked, Severity: SevInfo},
			{Rule: RuleStale, Severity: SevInfo},
		}}, want: 35},
		{name: "stale 200 days + orphaned", f: FileInfo{Findings: []Finding{
			{Rule: RuleUntracked, Severity: SevInfo},
			{Rule: RuleStale, Severity: SevWarn},
			{Rule: RuleOrphaned, Severity: SevWarn},
		}}, want: 70},
		{name: "stale 400 days", f: FileInfo{Findings: []Finding{
			{Rule: RuleUntracked, Severity: SevInfo},
			{Rule: RuleStale, Severity: SevError},
		}}, want: 55},
		{name: "empty dir", f: FileInfo{Findings: []Finding{
			{Rule: RuleUntracked, Severity: SevInfo},
			{Rule: RuleEmpty, Severity: SevInfo},
		}}, want: 50},
		{name: "tracked not stale", f: FileInfo{}, want: 0},
		{
			name: "all signals capped at 100",
			f: FileInfo{Findings: []Finding{
				{Rule: RuleUntracked, Severity: SevInfo},
				{Rule: RuleStale, Severity: SevError},
				{Rule: RuleLargeFile, Severity: SevError},
				{Rule: RuleTodoOnly, Severity: SevInfo},
				{Rule: RuleOrphaned, Severity: SevWarn},
				{Rule: RuleDuplicate, Severity: SevWarn},
			}},
			want: 100,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := Score(&tc.f)
			if got != tc.want {
				t.Errorf("Score() = %d, want %d", got, tc.want)
			}
		})
	}
}

// --- FindDuplicates tests ---

func TestFindDuplicates(t *testing.T) {
	files := []FileInfo{
		// Backup suffix: config-backup.yaml → config.yaml
		{RelPath: "config.yaml", Size: 100},
		{RelPath: "config-backup.yaml", Size: 100},
		// Basename collision: use non-common name with size > 4KB
		{RelPath: "processor.go", Size: 8192},
		{RelPath: "old/processor.go", Size: 8192},
		// Version suffix: readme-v2.md → readme.md
		{RelPath: "readme.md", Size: 50},
		{RelPath: "readme-v2.md", Size: 50},
		// Unique file: no duplicate
		{RelPath: "unique.txt", Size: 999},
		// Common multi-instance name: should NOT be flagged even with same size
		{RelPath: "cmd/foo/main.go", Size: 200},
		{RelPath: "cmd/bar/main.go", Size: 200},
		// Small basename collision (<=4KB): should NOT be flagged
		{RelPath: "helper.go", Size: 512},
		{RelPath: "lib/helper.go", Size: 512},
	}

	FindDuplicates(files)

	byPath := make(map[string]FileInfo)
	for _, f := range files {
		byPath[f.RelPath] = f
	}

	cases := []struct {
		path     string
		wantDup  string
		hasNoDup bool
	}{
		{path: "config.yaml", hasNoDup: true},
		{path: "config-backup.yaml", wantDup: "config.yaml"},
		{path: "processor.go", hasNoDup: true},
		{path: "old/processor.go", wantDup: "processor.go"},
		{path: "readme.md", hasNoDup: true},
		{path: "readme-v2.md", wantDup: "readme.md"},
		{path: "unique.txt", hasNoDup: true},
		// Common multi-instance: both should have no duplicate
		{path: "cmd/foo/main.go", hasNoDup: true},
		{path: "cmd/bar/main.go", hasNoDup: true},
		// Small files: no basename collision
		{path: "helper.go", hasNoDup: true},
		{path: "lib/helper.go", hasNoDup: true},
	}

	for _, tc := range cases {
		f := byPath[tc.path]
		if tc.hasNoDup {
			if f.Duplicate != "" {
				t.Errorf("%s: expected no duplicate, got %q", tc.path, f.Duplicate)
			}
		} else {
			if f.Duplicate != tc.wantDup {
				t.Errorf("%s: Duplicate = %q, want %q", tc.path, f.Duplicate, tc.wantDup)
			}
		}
	}
}

func TestFindDuplicatesWithHash(t *testing.T) {
	t.Parallel()
	// Create temp files with identical content but different names.
	dir := t.TempDir()
	content := strings.Repeat("duplicate content here\n", 300) // >4KB

	for _, name := range []string{"report.txt", "subdir/quarterly.txt", "archive/old-report.txt"} {
		p := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	// Add a unique file with same size but different content.
	unique := strings.Repeat("totally different text!\n", 300)
	if err := os.WriteFile(filepath.Join(dir, "unique.txt"), []byte(unique), 0o644); err != nil {
		t.Fatal(err)
	}

	files := []FileInfo{
		{Path: filepath.Join(dir, "report.txt"), RelPath: "report.txt", Size: int64(len(content))},
		{Path: filepath.Join(dir, "subdir/quarterly.txt"), RelPath: "subdir/quarterly.txt", Size: int64(len(content))},
		{Path: filepath.Join(dir, "archive/old-report.txt"), RelPath: "archive/old-report.txt", Size: int64(len(content))},
		{Path: filepath.Join(dir, "unique.txt"), RelPath: "unique.txt", Size: int64(len(unique))},
	}

	FindDuplicates(files)

	byPath := make(map[string]FileInfo)
	for _, f := range files {
		byPath[f.RelPath] = f
	}

	// report.txt has shortest path → original.
	if byPath["report.txt"].Duplicate != "" {
		t.Errorf("report.txt should be original, got duplicate=%q", byPath["report.txt"].Duplicate)
	}
	// Others should point to report.txt.
	if byPath["subdir/quarterly.txt"].Duplicate != "report.txt" {
		t.Errorf("quarterly.txt duplicate=%q, want report.txt", byPath["subdir/quarterly.txt"].Duplicate)
	}
	if byPath["archive/old-report.txt"].Duplicate != "report.txt" {
		t.Errorf("old-report.txt duplicate=%q, want report.txt", byPath["archive/old-report.txt"].Duplicate)
	}
	// Unique file should not be flagged.
	if byPath["unique.txt"].Duplicate != "" {
		t.Errorf("unique.txt should have no duplicate, got %q", byPath["unique.txt"].Duplicate)
	}
}

func TestMimeToClass(t *testing.T) {
	t.Parallel()
	tests := []struct {
		mime string
		want ContentClass
	}{
		{"application/json", ContentConfig},
		{"application/xml", ContentConfig},
		{"text/xml", ContentConfig},
		{"application/toml", ContentConfig},
		{"application/x-yaml", ContentConfig},
		{"text/x-yaml", ContentConfig},
		{"text/plain", ContentUnknown},
		{"image/png", ContentUnknown},
		{"application/octet-stream", ContentUnknown},
		{"application/pdf", ContentUnknown},
	}

	for _, tc := range tests {
		t.Run(tc.mime, func(t *testing.T) {
			t.Parallel()
			got := mimeToClass(tc.mime)
			if got != tc.want {
				t.Errorf("mimeToClass(%q) = %v, want %v", tc.mime, got, tc.want)
			}
		})
	}
}

func TestEmitFindings(t *testing.T) {
	t.Parallel()
	files := []FileInfo{
		{Tracked: false, StaleDays: 200, Orphaned: true, Size: 500, Content: ContentGenerated, Duplicate: "other.go"},
		{Tracked: true, Size: 50 * 1024 * 1024},
		{Tracked: true},
	}

	EmitFindings(files)

	// File 0: untracked + stale(warn) + orphaned + generated + duplicate = 5 findings
	if len(files[0].Findings) != 5 {
		t.Errorf("file 0: got %d findings, want 5", len(files[0].Findings))
	}
	if !files[0].HasFinding(RuleUntracked) {
		t.Error("file 0: missing untracked finding")
	}
	if !files[0].HasFinding(RuleStale) {
		t.Error("file 0: missing stale finding")
	}
	if !files[0].HasFinding(RuleOrphaned) {
		t.Error("file 0: missing orphaned finding")
	}
	if !files[0].HasFinding(RuleGenerated) {
		t.Error("file 0: missing generated finding")
	}
	if !files[0].HasFinding(RuleDuplicate) {
		t.Error("file 0: missing duplicate finding")
	}

	// File 1: tracked, 50MB → large-file(warn) only
	if len(files[1].Findings) != 1 {
		t.Errorf("file 1: got %d findings, want 1", len(files[1].Findings))
	}
	if !files[1].HasFinding(RuleLargeFile) {
		t.Error("file 1: missing large-file finding")
	}

	// File 2: tracked, no signals → 0 findings
	if len(files[2].Findings) != 0 {
		t.Errorf("file 2: got %d findings, want 0", len(files[2].Findings))
	}
}

func TestFindingHelpers(t *testing.T) {
	t.Parallel()
	f := &FileInfo{}
	if f.HasFinding(RuleStale) {
		t.Error("empty file should not have stale finding")
	}
	f.AddFinding(Finding{Source: "test", Rule: RuleStale, Severity: SevWarn})
	if !f.HasFinding(RuleStale) {
		t.Error("should have stale finding after AddFinding")
	}
	if f.HasFinding(RuleOrphaned) {
		t.Error("should not have orphaned finding")
	}
}
